import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Alpine Explorer Backpack",
    price: 129.99,
    category: "backpacks",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 42,
    shortDescription: "Durable 65L backpack with waterproof construction",
    isNew: true,
    isFeatured: true,
  },
  {
    id: "2",
    name: "TrailMaster Hiking Backpack",
    price: 89.99,
    category: "backpacks",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 28,
    shortDescription: "Lightweight 45L pack with hydration system",
  },
  {
    id: "3",
    name: "DayTripper Backpack",
    price: 59.99,
    category: "backpacks",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 36,
    shortDescription: "Compact 25L backpack for day hikes",
    isOnSale: true,
    salePrice: 49.99,
  },
  {
    id: "4",
    name: "Summit 3-Person Tent",
    price: 249.99,
    category: "tents",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 19,
    shortDescription: "All-season tent with quick setup design",
    isFeatured: true,
  },
  {
    id: "5",
    name: "Wilderness 2-Person Tent",
    price: 199.99,
    category: "tents",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 24,
    shortDescription: "Ultralight tent for backpacking adventures",
  },
  {
    id: "6",
    name: "Family Basecamp 6-Person Tent",
    price: 349.99,
    category: "tents",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 15,
    shortDescription: "Spacious tent with separate rooms and vestibule",
    isNew: true,
  },
  {
    id: "7",
    name: "Alpine Hiking Boots",
    price: 159.99,
    category: "footwear",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 31,
    shortDescription: "Waterproof boots with Vibram soles",
    isFeatured: true,
  },
  {
    id: "8",
    name: "TrailRunner Pro Shoes",
    price: 129.99,
    category: "footwear",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 27,
    shortDescription: "Lightweight trail running shoes with grip",
  },
  {
    id: "9",
    name: "Waterproof Hiking Sandals",
    price: 79.99,
    category: "footwear",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 18,
    shortDescription: "Versatile sandals for water and trail",
    isOnSale: true,
    salePrice: 69.99,
  },
  {
    id: "10",
    name: "All-Weather Jacket",
    price: 199.99,
    category: "clothing",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 23,
    shortDescription: "3-layer waterproof and breathable shell",
    isFeatured: true,
  },
  {
    id: "11",
    name: "Fleece Pullover",
    price: 69.99,
    category: "clothing",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 34,
    shortDescription: "Warm mid-layer with quarter zip",
  },
  {
    id: "12",
    name: "Convertible Hiking Pants",
    price: 79.99,
    category: "clothing",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 29,
    shortDescription: "Quick-dry pants that convert to shorts",
  },
  {
    id: "13",
    name: "Trekking Poles (Pair)",
    price: 49.99,
    category: "accessories",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 21,
    shortDescription: "Adjustable aluminum poles with cork grips",
  },
  {
    id: "14",
    name: "Wilderness First Aid Kit",
    price: 29.99,
    category: "accessories",
    image: "/placeholder.svg?height=400&width=600",
    rating: 5,
    reviewCount: 42,
    shortDescription: "Comprehensive kit for outdoor emergencies",
    isNew: true,
  },
  {
    id: "15",
    name: "Insulated Water Bottle",
    price: 34.99,
    category: "accessories",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 38,
    shortDescription: "32oz vacuum insulated stainless steel bottle",
  },
  {
    id: "16",
    name: "Solar Camping Lantern",
    price: 39.99,
    category: "accessories",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4,
    reviewCount: 17,
    shortDescription: "Rechargeable LED lantern with USB output",
  },
]